# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('total_contribution', otree.db.models.CurrencyField(null=True)),
                ('individual_share', otree.db.models.CurrencyField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgg_conditional_group', to='otree.Session')),
            ],
            options={
                'db_table': 'PGG_Conditional_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('response_0', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 0,0 €?')),
                ('response_3', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 3,0 €?')),
                ('response_6', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 6,0 €?')),
                ('response_9', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 9,0 €?')),
                ('response_12', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 12,0 €?')),
                ('response_15', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 15,0 €?')),
                ('response_18', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 18,0 €?')),
                ('response_21', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 21,0 €?')),
                ('response_24', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 24,0 €?')),
                ('response_27', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 27,0 €?')),
                ('response_30', otree.db.models.CurrencyField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12), (15, 15), (18, 18), (21, 21), (24, 24), (27, 27), (30, 30)], null=True, verbose_name='How much would you contribute if your two teammates on average contribute 30,0 €?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PGG_Conditional.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgg_conditional_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgg_conditional_player', to='otree.Session')),
            ],
            options={
                'db_table': 'PGG_Conditional_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgg_conditional_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'PGG_Conditional_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGG_Conditional.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGG_Conditional.Subsession'),
        ),
    ]
